pipeline {
    agent {
        docker {
            image 'node:6-alpine' 
            args '-p 3000:3000' 
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'cd admin-web'
                sh 'sh test.sh'
                sh 'yarn install' 
            }
        }
    }
}
