pipeline {
    agent {
        docker {
            image 'node:12-alpine' 
            args '-p 3000:3000' 
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'yarn install'
                echo '打包完成，准备构建docker'
            }
        }
    }
}
node{
    stage('docker镜像构建') { 
      dir('./shell'){
        sh 'cp -r ../dist ./'
        def customImage = docker.build("base-adnub-web")
        customImage.inside {
            sh 'make test'
        }
      }
    }
}
