pipeline {
    agent {
        docker {
            image 'node:12-alpine' 
            args '-p 3000:3000' 
        }
    }
    stages {
        stage('Build') { 
            steps {
                sh 'yarn install'
                sh 'yarn build'
            }
        }
        def customImage = docker.build("bas-admin-web")
        customImage.inside {
            sh 'make test'
        }
    }
}
